import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import React from "react";
import { Flex, Grid, Theme } from "@radix-ui/themes";
import { Sidebar } from "@/components/Sidebar";
import { ThemeProvider } from "next-themes";
import NoSSR from "@/components/NoSSR";
import { Titlebar } from "@/components/Titlebar";
import { cn } from "@/utils/cn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={"h-screen min-h-screen max-h-screen"}>
    <NoSSR>
      <ThemeProvider attribute={"class"}>
        <Theme appearance="dark" panelBackground="translucent">
          <Grid width={"100%"} height={"100vh"} rows={"1.5rem minmax(0, 1fr)"} columns={"4rem 1fr"}>
            <div></div>
            <Titlebar/>
            <Sidebar/>
            {children}
          </Grid>
        </Theme>
      </ThemeProvider>
    </NoSSR>
    </body>
    </html>
  );
}